### PR TITLE
allow to customize pwdb location

### PR DESCRIPTION
**Pull request by indeyets**

### CODE REVIEW

**Comment by stilliard** [comment]
Hi @indeyets ,
Sorry i haven't replied to this earlier. 
I like this feature but would it solve anything that a volume to the db file would not solve? e.g. https://docs.docker.com/engine/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume

**Comment by indeyets** [comment]
I think I tried it and had some issue. But I can't remember what that issue was. I'll try to give it another test

**Comment by stilliard** [comment]
Thanks @indeyets

**Comment by OmgImAlexis** [comment]
This simply moves the file within the docker container, you'll still need to map the file to the host so this doesn't actually change anything.

**Comment by stilliard** [comment]
Closing for now, but please reopen if needed :+1:

**Pull request closed without merging**
