### PR TITLE
SSL/TLS ENV #27

### PR DESCRIPTION
**Pull request by NicoAiko**
#27

### CODE REVIEW

**Comment by NicoAiko** [comment]
When setting the ENV variable in the run command, it must be done this way: 
-e "TLS=--tls=2"

Only the number isn't enough!

**Comment by NicoAiko** [comment]
@stilliard 
are you getting mails of this?

**Comment by stilliard** [comment]
Hi @NicoAiko , sorry I haven't replied to your pull request yet. 
I like the work you've done for it, I have an idea to work off this to maybe instead of using an ENV var, we could detect you're passing in the flag as part of the command run with docker run and override this way. 
I'll see if I can get something together soon.

**Comment by stilliard** [comment]
Closing ref #27

**Pull request closed without merging**
