### PR TITLE
Upgrade to debian:buster-slim

### PR DESCRIPTION
**Pull request by EthraZa**
**Upgrade to Debian 10 Slim.**

- Add libmariadb3 to build pure-ftpd-mysql_*.deb.
- Add perl dependency. (Really?)
- Add other pure-ftpd compiled deb files to Dockerfile commented out just to help people wanting to build image with DB support

Fix to #142
Maybe help #130

### CODE REVIEW

**Comment by EthraZa** [comment]
The second commit adds the https://github.com/naitso/ftpUserManager shell script that may help people administrate pure-ftpd virtual users as in #140

**Comment by stilliard** [comment]
Hey @EthraZa 
This looks great! 
My only issue with the ftpUserManager script is it doesn't have a licence, without one we can't package it with our container sorry.

**Comment by EthraZa** [comment]
That's true. Didn't noticed the lack of license. But can you merge just c804f28 or do I need to do some modification?

**Comment by EthraZa** [comment]
About ftpUserManager I'm thinking in build an inspired script that uses [shell2http](https://github.com/msoap/shell2http) anyways.

**Comment by stilliard** [comment]
@EthraZa sure best to open a new PR for a new script to be included, if you remove that other commit and force push (ref https://stackoverflow.com/a/51400593) I can test & merge the first one as it looks great thanks :)

**Comment by EthraZa** [comment]
Done

**Comment by stilliard** [comment]
Thanks @EthraZa ! Awesome work on this :+1:

**Comment by stilliard** [comment]
Docker hub is currently building the new latest tag & a new "buster-latest" tag for this. 
Once that's done I'll upgrade the hardened branch/tag as well.
Thanks again.

**Pull request merged**
